# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA2016/DEMO/starfire.cache/wt [current_project]
set_property parent.project_path F:/FPGA2016/DEMO/starfire.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths E:/FPGA_Project/KCT16/KCT16.ipdefs [current_project]
add_files F:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files F:/FPGA2016/DEMO/starfire.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib F:/FPGA2016/DEMO/starfire.srcs/sources_1/src/starfire_top.vhd
read_xdc F:/FPGA2016/DEMO/starfire.srcs/constrs_1/new/starfire_top.xdc
set_property used_in_implementation false [get_files F:/FPGA2016/DEMO/starfire.srcs/constrs_1/new/starfire_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file starfire_top.hwdef }
synth_design -top starfire_top -part xc7z020clg484-1
write_checkpoint -noxdef starfire_top.dcp
catch { report_utilization -file starfire_top_utilization_synth.rpt -pb starfire_top_utilization_synth.pb }
