# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA_Project/host_system/ULC64GHost.cache/wt [current_project]
set_property parent.project_path E:/FPGA_Project/host_system/ULC64GHost.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  E:/FPGA_Project/host_system/ULC64GHost.ipdefs/Stator_interface_1.0
  E:/FPGA_Project/host_system/ULC64GHost.ipdefs/ECG_interface_1.0
} [current_project]
add_files E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/can_ramInit.coe
add_files E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/ecg_database.coe
add_files E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/TILT_LMT.coe
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/ECG_dataOut_synth_1/ECG_dataOut.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/ECG_dataOut_synth_1/ECG_dataOut.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/RAM_256X80_synth_1/RAM_256X80.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/RAM_256X80_synth_1/RAM_256X80.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/TILT_LMT_ROM_synth_1/TILT_LMT_ROM.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/TILT_LMT_ROM_synth_1/TILT_LMT_ROM.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/ecg_database_synth_1/ecg_database.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/ecg_database_synth_1/ecg_database.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/eeprom_512X8_fifo_synth_1/eeprom_512X8_fifo.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/eeprom_512X8_fifo_synth_1/eeprom_512X8_fifo.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/fifo_2048X16_synth_1/fifo_2048X16.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/fifo_2048X16_synth_1/fifo_2048X16.dcp]
add_files -quiet E:/FPGA_Project/host_system/ULC64GHost.runs/multiply_16X8_bit_synth_1/multiply_16X8_bit.dcp
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.runs/multiply_16X8_bit_synth_1/multiply_16X8_bit.dcp]
add_files E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib {
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/project_pkg.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/SJA1000.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/SJA_REG_interface.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/slipring/crc_32.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/check_rise_edge.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/check_fall_edge.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/pulse_generator.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/ecg/find_max_min_rwave.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/slipring/slipring_comm.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/LED/serial_out.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/FRAM/cycle_operation.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/couch_bcd2bin.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/CAN_data_transceiver.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/LED/bcd_decoder.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_encoder_counter5.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/feq_meter_v4.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/adc/adc.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/error_check.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/pwm_gen.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/auto_adjust.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/signal_lpf.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/generate_rot_velocity.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/ecg/find_rwave.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/RS485/rs485_tran.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/RS485/rs485_rec.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/err_handling/mux2_gate.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/slipring/hotlink_interface.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/err_handling/gen_RS_signal.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/couch/encoder_counter_v5.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/FRAM/eeprom_wrrd.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/LED/display_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/can_interface.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/Build_ver.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/LED/bcdtobin.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_relay_check.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_protect.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_limit.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_bin2bcd.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_ang_calc.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_angle_set.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/peripheral/temperature_rec.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/rot_protect.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/rot_para_calc.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/encoder.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/dac.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/adc/adc_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/adc/adc_average.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/couch/anti_15ms_glitch.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/rotate_ctrl.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/ecg/ecg_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/RS485/rs485_ctrl.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/LED/led_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/slipring/hotlink_ctrl.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/FRAM/ghost_ctrl_fram.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/fview_err_detect.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/err_handling/error_handling.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/FRAM/eeprom_control.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/couch/couch_ctrl.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/combin_reg_ctrl.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/combin_cmd_ctrl.VHD
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/CAN/can_trans_ctrl.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/tilt/tilt_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/peripheral/Temperature_humidity_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/rotation/rotation_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/peripheral/navigator_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/adc/adc_filter.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/anti_glitch.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/peripheral/Light_strip.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/comm_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/couch/input_delay.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/gantry_control.vhd
  E:/FPGA_Project/host_system/ULC64GHost.srcs/sources_1/src/KCT16_top.vhd
}
read_xdc E:/FPGA_Project/host_system/ULC64GHost.srcs/constrs_1/ULC64_GHOST.xdc
set_property used_in_implementation false [get_files E:/FPGA_Project/host_system/ULC64GHost.srcs/constrs_1/ULC64_GHOST.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file ULC64GHost.hwdef }
synth_design -top ULC64GHost -part xc7z020clg484-1
write_checkpoint -noxdef ULC64GHost.dcp
catch { report_utilization -file ULC64GHost_utilization_synth.rpt -pb ULC64GHost_utilization_synth.pb }
